# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|
  
  config.vm.provision "shell", path: "bootstrap.sh"

  NodeCount = 1

  (1..NodeCount).each do |i|

    config.vm.define "terraform#{i}" do |terraform|
      terraform.vm.box = "bento/ubuntu-20.04"
      terraform.vm.hostname = "terraform#{i}"
      terraform.vm.network "private_network", ip: "192.168.56.11#{i}"
      terraform.vm.synced_folder ".", "/vagrant", type: "virtualbox"
      terraform.vm.provider "virtualbox" do |v|
        v.name = "terraform#{i}"
        v.gui = false
        v.memory = 2048
        v.cpus = 1      
      end

    end

  end

end
